- hosts: all
  become: true
  tasks:
    - name: create the 'ichrak' user
      user: name=ichrak append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ichrak' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ichrak ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'


