# Generated by Django 3.2.16 on 2023-02-28 23:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0005_alter_team_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_name', models.CharField(max_length=255)),
                ('qte', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='qualifeed.box')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caracterstic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caracterstic_label', models.CharField(max_length=255)),
                ('caracterstic_value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, null=True, size=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_control', models.DateField()),
                ('details_control', models.CharField(max_length=100)),
                ('time_control', models.TimeField()),
                ('state_control', models.CharField(max_length=100)),
                ('photo_control', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defect_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('defect_type_value', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_reperation', models.DateField()),
                ('details_reperation', models.CharField(max_length=100)),
                ('time_reperation', models.TimeField()),
                ('state_reperation', models.CharField(max_length=100)),
                ('photo_reperation', models.ImageField(upload_to='')),
                ('defect_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qualifeed.defect')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='qualifeed.productcategory')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_code', models.CharField(max_length=255)),
                ('type_code', models.CharField(choices=[('QrCode', 'QRCODE'), ('ZebraCode', 'ZebraCode'), ('BarCode', 'BarCode')], max_length=255)),
                ('format_of_code', models.CharField(max_length=255)),
                ('photo_code', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=500)),
                ('photo_product', models.ImageField(upload_to='')),
                ('status', models.CharField(max_length=100)),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.box')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.brand')),
                ('caracterstics', models.ManyToManyField(to='qualifeed.Caracterstic')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.productcategory')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_invoice', models.CharField(max_length=100)),
                ('date_invoice', models.DateField()),
                ('id_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.control')),
                ('id_reperation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.reperation')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('defect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.defect')),
                ('serial_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.product')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='have_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_tag', models.CharField(max_length=255)),
                ('serial_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.product')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.caracterstic')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defect_type_name', models.CharField(max_length=100)),
                ('defect_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, null=True, size=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.defecttype'),
        ),
        migrations.AddField(
            model_name='defect',
            name='products',
            field=models.ManyToManyField(related_name='defects', to='qualifeed.Product'),
        ),
        migrations.AddField(
            model_name='defect',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='control',
            name='defect_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qualifeed.defect'),
        ),
        migrations.AddField(
            model_name='control',
            name='serial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.product'),
        ),
        migrations.AddField(
            model_name='control',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='control',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CheckControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threshold', models.IntegerField()),
                ('post', models.CharField(blank=True, max_length=100, null=True)),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.box')),
                ('defect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualifeed.defect')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
