apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-qualifeed
  labels:
    app: polls
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
